.TH RUN-JOB 1 "2026-03-17" "toolbox" "Toolbox Commands"

.SH NAME
run-job \- execute a toolbox pipeline job

.SH SYNOPSIS
.B run-job
.IR PIPELINE
.IR INPUT
.RI [ --env " NAME=VALUE " ...]

.SH DESCRIPTION
The
.B run-job
command executes a pipeline defined in the toolbox.

A new job directory is created under:

.EX
/toolbox/jobs/
.EE

Each job contains the following structure:

.EX
input/
work/
output/
log.txt
status
meta.env
.EE

Optional
.B --env
arguments allow environment overrides for a specific job execution.

.SH EXAMPLES

Run PDF OCR pipeline:

.EX
run-job pdf-ocr /toolbox/shared/document.pdf
.EE

Run image OCR and translation with explicit language overrides:

.EX
run-job image-ocr-translate /toolbox/shared/page.png \\
  --env TESSERACT_OCR_LANG=por \\
  --env GOOGLE_TRANSLATE_SOURCE_LANG=pt \\
  --env GOOGLE_TRANSLATE_TARGET_LANG=en
.EE

.SH FILES

.TP
.B /toolbox/jobs
Directory containing all executed jobs.

.SH SEE ALSO
.BR job-inspect (1)

.SH AUTHOR
Thiago Ribeiro
